-- CREATES DATABASE AND TABLE STATES

CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
USE hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS states (
	id INT IS NOT NULL PRIMARY KEY AUTO_INCREMENT UNIQUE,
	name VARCHAR(256) IS NOT NULL
);
